services:
  app-default:
    image: ovis22/docker-quotes:v1.1.0
    container_name: quotes-default
    restart: "no"
    build: .
    environment:
      - APP_MODE=bash
      - QUOTES=Welcome to Docker Quotes;Keep it simple;Containers are cool;Build, Ship, and Run Any App, Anywhere
      - FONT_NAME=standard

  app-starwars:
    image: ovis22/docker-quotes:v1.1.0
    container_name: quotes-starwars
    restart: "no"
    build: .
    depends_on:
      app-default:
        condition: service_completed_successfully
    environment:
      - APP_MODE=python
      - QUOTES=ITS A TRAP;I am your father;I find your lack of faith disturbing;May the Force be with you;Do or do not, there is no try;Use the Force, Luke
      - FONT_NAME=starwars

  app-polish-songs:
    image: ovis22/docker-quotes:v1.1.0
    container_name: quotes-polish-songs
    restart: "no"
    build: .
    depends_on:
      app-starwars:
       condition: service_completed_successfully
    environment:
      - QUOTES=Mniej niz zero;Dni ktorych nie znamy;Chociaz dookola wszyscy juz posneli;Wazne sa tylko te dni ktorych jeszcze nie znamy;Szklana pogoda;Autobiografia;Mydelko Fa
      - FONT_NAME=Doom
